import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export function TermsAndConditions() {
  return (
    <Card className="w-full bg-white/95 border-white/20">
      <CardHeader>
        <CardTitle className="text-2xl font-bold text-black text-center">
          Terms & Conditions
        </CardTitle>
      </CardHeader>
      <CardContent>
        <div className="space-y-4 text-black text-sm">
          <div>
            <div>
              <h3 className="font-semibold text-fpl-green mb-2">1. Electronic Record</h3>
              <p>
                This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
              </p>
            </div>

            <div>
              <h3 className="font-semibold text-fpl-green mb-2">2. Platform Information</h3>
              <p>
                This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name https://fantasypicks.onrender.com/ ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').
              </p>
            </div>

            <div>
              <h3 className="font-semibold text-fpl-green mb-2">3. Platform Ownership</h3>
              <p>
                The Platform is owned by MR GANESH B, a company incorporated under the Companies Act, 1956 with its registered office at G-19 20th Main road, Palani Muthu Towers 1st floor, Annanagar Chennai 600040, Chennai, India (hereinafter referred to as 'Platform Owner', 'we', 'us', 'our').
              </p>
            </div>

            <div>
              <h3 className="font-semibold text-fpl-green mb-2">4. Binding Agreement</h3>
              <p>
                Your use of the Platform and services and tools are governed by the following terms and conditions as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations.
              </p>
            </div>

            <div>
              <h3 className="font-semibold text-fpl-green mb-2">5. Terms of Use</h3>
              <div className="space-y-2">
                <p><strong>• Account Accuracy:</strong> To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.</p>
                
                <p><strong>• No Warranty:</strong> Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services.</p>
                
                <p><strong>• Use at Own Risk:</strong> Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner.</p>
                
                <p><strong>• Intellectual Property:</strong> The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents.</p>
                
                <p><strong>• Payment:</strong> You agree to pay us the charges associated with availing the Services.</p>
                
                <p><strong>• Lawful Use:</strong> You agree not to use the Platform and/or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.</p>
              </div>
            </div>

            <div>
              <h3 className="font-semibold text-fpl-green mb-2">6. Indemnification</h3>
              <p>
                You shall indemnify and hold harmless Platform Owner, its affiliates, group companies and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorney's fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies.
              </p>
            </div>

            <div>
              <h3 className="font-semibold text-fpl-green mb-2">7. Governing Law</h3>
              <p>
                These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India. All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Chennai and Tamil Nadu.
              </p>
            </div>

            <div>
              <h3 className="font-semibold text-fpl-green mb-2">8. Contact Information</h3>
              <p>
                All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.
              </p>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
